apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque # Default: Key-value pairs
data:
  mongo-root-username: dXNlcm5hbWU= #username in base64
  mongo-root-password: cGFzc3dvcmQ= #password in base64